// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722104150_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("islem_turu");

                    b.Property<int?>("CandidatePointId")
                        .HasColumnType("integer")
                        .HasColumnName("aday_nokta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("islem_tarihi");

                    b.Property<int?>("GatheringAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("toplanma_alani_id");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("yeni_degerler");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("eski_degerler");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidatePointId");

                    b.HasIndex("GatheringAreaId");

                    b.ToTable("islem_gecmisi");
                });

            modelBuilder.Entity("backend.Models.CandidatePoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<double>("AlanM2")
                        .HasColumnType("double precision")
                        .HasColumnName("alan_m2");

                    b.Property<string>("AlanTur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alan_tur");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturulma_tarihi");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("karar_tarihi");

                    b.Property<int?>("GatheringAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("toplanma_alani_id");

                    b.Property<string>("IlceAdi")
                        .HasColumnType("text")
                        .HasColumnName("ilce_adi");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("kabul_edildi");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer")
                        .HasColumnName("kapasite");

                    b.Property<string>("MahalleAdi")
                        .HasColumnType("text")
                        .HasColumnName("mahalle_adi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Point>("PointWkt")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("point_wkt");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("ret_nedeni");

                    b.HasKey("Id");

                    b.HasIndex("GatheringAreaId");

                    b.HasIndex("PointWkt");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PointWkt"), "gist");

                    b.ToTable("aday_noktalar");
                });

            modelBuilder.Entity("backend.Models.ToplanmaAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AlanM2")
                        .HasColumnType("double precision")
                        .HasColumnName("alan_m2");

                    b.Property<string>("AlanTur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alan_tur");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silinme_tarihi");

                    b.Property<string>("IlceAdi")
                        .HasColumnType("text")
                        .HasColumnName("ilce_adi");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer")
                        .HasColumnName("kapasite");

                    b.Property<string>("MahalleAdi")
                        .HasColumnType("text")
                        .HasColumnName("mahalle_adi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Point>("PointWkt")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("point_wkt");

                    b.HasKey("Id");

                    b.HasIndex("PointWkt");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PointWkt"), "gist");

                    b.ToTable("toplanma_alanlari");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginVerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LoginVerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.ActivityLog", b =>
                {
                    b.HasOne("backend.Models.CandidatePoint", "CandidatePoint")
                        .WithMany()
                        .HasForeignKey("CandidatePointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.ToplanmaAlani", "GatheringArea")
                        .WithMany()
                        .HasForeignKey("GatheringAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CandidatePoint");

                    b.Navigation("GatheringArea");
                });

            modelBuilder.Entity("backend.Models.CandidatePoint", b =>
                {
                    b.HasOne("backend.Models.ToplanmaAlani", "GatheringArea")
                        .WithMany()
                        .HasForeignKey("GatheringAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GatheringArea");
                });
#pragma warning restore 612, 618
        }
    }
}
